
==== Configuration Properties


In previous versions of the plugin configuration was specified using the `grails.mongo` prefix. This is now `grails.mongodb` instead. For example, the following configuration in `application.groovy` or `Config.groovy`:

[source,groovy]
----
grails {
    mongo {
        databaseName = 'foo'
    }
}
----

Should now be expressed as:

[source,groovy]
----
grails {
    mongodb {
        databaseName = 'foo'
    }
}
----


==== Persistence Engine


Since GORM for MongoDB 5.0 there is now a choice of persistence engine. The original GORM for MongoDB converted MongoDB documents to and from Groovy objects. This engine is still present and can be activated with the following configuration in `grails-app/conf/application.yml`:

[source,groovy]
----
grails:
    mongodb:
        engine: mapping
----

However, 5.0 and above uses a new engine based on MongoDB 3.x driver codecs which means objects are no longer converted first to MongoDB Document objects and then to Groovy objects, instead the driver reads Groovy objects directly from the JSON stream at the driver level, which is far more efficient, however may not exhibit exactly the same behaviour as the previous version. To active this new engine use the following codec (or leave it blank as the codec engine is now the default):

[source,groovy]
----
grails:
    mongodb:
        engine: codec
----

WARNING: When switching from mapping to codec with an existing database, there are several conditions that may require manual changes.

1. Embedded bi-directional one to many associations will need a back-reference created if one does not exist.
2. The version property of all documents, including embedded, may need to have it's type changed.
3. The codec engine is more strict about data types than the mapping engine. For example, data stored in mongo as an `INT32` could be converted to a `BigDecimal`. This is no longer possible and the data will need to be changed. Other examples include strings like "1470924116786" could be converted to `Date` objects in the mapping engine, but will not work in the codec engine. While testing your application, you can identify these types of issues by the error message that will occur.

Here is an example of an embedded bi-directional one to many relationship that may require manual migration:

[source,groovy]
----
class Bar {
    static belongsTo = [fooBar: Foo]
}
class Foo {
    static hasMany = [bars: Bar]
    static embedded = ['bars']
}
----

An example script to set that back reference would be:

[source,javascript]
----
db.foo.find({"$where": "this.bars && this.bars.length > 0"}).forEach(function(foo) {
    for (var i = 0; i < foo.bars.length; i++) {
        foo.bars[i].fooBar = foo._id;
    }
    db.foo.save(foo);
});
----

An example script to update the version property of top level documents is:

[source,javascript]
----
db.getCollectionNames().forEach(function (c) {
    var collection = db.getCollection(c);
    collection.find({version: {$type: 16}}).forEach(function(domain) {
        domain.version = new NumberLong(domain.version);
        collection.save(domain);
    });
});
----

NOTE: Embedded documents may also require updating.