If you wish to use GORM for MongoDB outside of a Grails application you should declare the necessary dependencies, for example in Gradle:

[source,groovy]
----
compile "org.grails:grails-datastore-gorm-mongodb:VERSION"
----

Then annotate your entities with the `grails.gorm.annotation.Entity` annotation:

[source,groovy]
----
@Entity
class Person {
    String name
}
----

Then you need to place the bootstrap logic somewhere in the loading sequence of your application which uses `MongoDbDataStoreSpringInitializer`:

[source,groovy]
----
def initializer = new MongoDbDataStoreSpringInitializer(Person)
def applicationContext = initializer.configure()

println Person.count()
----

For configuration you can either pass a map or an instance of the `org.springframework.core.env.PropertyResolver` interface:

[source,groovy]
----
def initializer = new MongoDbDataStoreSpringInitializer(['grails.mongodb.url':'http://myserver'], Person)
def applicationContext = initializer.configure()

println Person.count()
----

If you are using Spring with an existing `ApplicationContext` you can instead call `configureForBeanDefinitionRegistry` prior to refreshing the context. You can pass the Spring `Environment` object to the constructor for configuration:

[source,groovy]
----
ApplicationContext myApplicationContext = ...
def initializer = new MongoDbDataStoreSpringInitializer(myApplicationContext.getEnvironment(), Person)
initializer.configureForBeanDefinitionRegistry(myApplicationContext)

println Person.count()
----