To write unit tests with MongoDB and Spock you can simply extend from `grails.test.mongodb.MongoSpec`.

`MongoSpec` is an abstract class that will initialise GORM in the setup phase of the specification being executed. It
uses by default a `MongoClient` instance that connects to a MongoDB instance as defined in your configuration
(by default, `localhost` and port `27017`, see <<gettingStarted>> for more details):

[source,groovy]
----
include::{sourcedir}/examples/grails3-mongodb/src/test/groovy/functional/tests/LocalMongoUnitSpec.groovy[tags=structure]
----

You can also provide your own `MongoClient` instance to use something such as https://github.com/fakemongo/fongo[Fongo],
as shown in the following example:

[source,groovy]
----
include::{sourcedir}/examples/grails3-mongodb/src/test/groovy/functional/tests/BookUnitSpec.groovy[]
----

Note that the default implementation is to scan your classpath searching for domain classes, from the package defined
in the configuration property `grails.codegen.defaultPackage`, and all the way down its subpackages. If your application
is large, classpath scanning may be slow, so it's better to override the method `getDomainClasses()`:

[source,groovy]
----
include::{sourcedir}/examples/grails3-hibernate5-mongodb/src/test/groovy/functional/tests/BookFongoSpec.groovy[tags=getDomainClasses,indent=0]
----
